const mongoose = require("mongoose");
const { Schema } = mongoose;

const bootcampSchema = new Schema({
  title: String,
  company: String,
  location: Object,
  city: Array,
  virtual: Boolean,
  durationType: Object,
  fullTime: Object,
  partTime: Object,
  weeksLength: Number,
  totalAmountOfHours: Number,
  free: Boolean,
  tuitionFee: Number,
  financialDiscounts: Object,
  earlyPayment: Boolean,
  available:Boolean,
  amount:Number,
  womenDiversity: Boolean,
  available:Boolean,
  amount:Number,
  laptonLoan: Boolean,
  childCare:Boolean,
  installmentPaymentPlan: Object,
  available: Boolean,
  numberOfInstallments: Number,
  deposit: Boolean,
  depositFee: Number,
  additionalFee:Number,
  additionalInfo: Object,
  applicationCycles: Object,
  manchester: Number,
  london: Number,
  bristol:Number,
  birmingham:Number,
  leeds:Number,
  certification: Boolean,
  applicationlink: Object,
  manchester: String,
  london: String,
  bristol:String,
  birmingham:String,
  leeds:String,
  contactDetails: Object,
  emailAddress: String,
  telephoneNumber:String,
});

mongoose.model("bootcamps", bootcampSchema);
