const mongoose = require("mongoose");
const { Schema } = mongoose;

const bootcampSchema = new Schema({
  title: String,
  company: String,
  location: Object,
  city: String,
  durationType:String,
  durationDetails:Object,
  weeksLength: Number,
  totalAmountOfHours: Number,
  imageLinks:Object,
  logo:String,
  free: Boolean,
  tuitionFee: Number,
  financialDiscounts: Object,
  earlyPayment: Boolean,
  available:Boolean,
  amount:Number,
  womenDiversity: Boolean,
  available:Boolean,
  amount:Number,
  laptonLoan: Boolean,
  childCare:Boolean,
  installmentPaymentPlan: Object,
  available: Boolean,
  numberOfInstallments: Number,
  deposit: Boolean,
  depositFee: Number,
  additionalFee:Number,
  additionalInfo: Object,
  applicationCycles: Number,
  certification: Boolean,
  applicationlink: String,
  contactDetails: Object,
  emailAddress: String,
  telephoneNumber:String,
});

mongoose.model("bootcamps", bootcampSchema);
